/**
 * Стабильные коды ошибок API (поле `code` в JSON). Текст в `error` может быть локализован.
 */
export const ApiErrorCode = Object.freeze({
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN_ADMIN: 'FORBIDDEN_ADMIN',
  CSRF_INVALID: 'CSRF_INVALID',
  INTERNAL: 'INTERNAL',
  VALIDATION: 'VALIDATION',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  RATE_LIMITED: 'RATE_LIMITED',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
  PROBE_PATH_REQUIRED: 'PROBE_PATH_REQUIRED',
  PROBE_PATH_INVALID: 'PROBE_PATH_INVALID',
  PROBE_PATH_UNREADABLE: 'PROBE_PATH_UNREADABLE',
  ADMIN_SOURCE_NAME_PATH: 'ADMIN_SOURCE_NAME_PATH',
  ADMIN_SOURCE_NOT_FOUND: 'ADMIN_SOURCE_NOT_FOUND',
  FACET_INVALID: 'FACET_INVALID',
  BOOK_NOT_FOUND: 'BOOK_NOT_FOUND',
  SHELF_NOT_FOUND: 'SHELF_NOT_FOUND',
  BATCH_NO_BOOKS: 'BATCH_NO_BOOKS',
  BATCH_MAX_BOOKS: 'BATCH_MAX_BOOKS',
  BATCH_NO_SHELVES: 'BATCH_NO_SHELVES',
  BATCH_MAX_SHELVES: 'BATCH_MAX_SHELVES',
  BATCH_NO_MATCHING: 'BATCH_NO_MATCHING',
  BATCH_NO_MATCHING_IN_LIST: 'BATCH_NO_MATCHING_IN_LIST',
  BATCH_BOOKS_NOT_FOUND: 'BATCH_BOOKS_NOT_FOUND',
  BATCH_MAX_SEND: 'BATCH_MAX_SEND',
  BATCH_SCOPE_FACET_ONLY: 'BATCH_SCOPE_FACET_ONLY',
  BATCH_SCOPE_MISSING: 'BATCH_SCOPE_MISSING',
  BATCH_DOWNLOAD_MAX: 'BATCH_DOWNLOAD_MAX',
  BATCH_DOWNLOAD_IN_PROGRESS: 'BATCH_DOWNLOAD_IN_PROGRESS',
  BATCH_ARCHIVE_ERROR: 'BATCH_ARCHIVE_ERROR',
  SEND_IN_PROGRESS: 'SEND_IN_PROGRESS',
  SEND_NO_ATTACHMENTS: 'SEND_NO_ATTACHMENTS',
  EREADER_EMAIL_MISSING: 'EREADER_EMAIL_MISSING',
  EREADER_EMAIL_DENIED: 'EREADER_EMAIL_DENIED',
  SMTP_NOT_CONFIGURED: 'SMTP_NOT_CONFIGURED',
  FACET_AUTHOR_NOT_FOUND: 'FACET_AUTHOR_NOT_FOUND',
  FACET_SERIES_NOT_FOUND: 'FACET_SERIES_NOT_FOUND',
  PROFILE_INVALID_EMAIL: 'PROFILE_INVALID_EMAIL',
  BOOKMARK_INVALID_ID: 'BOOKMARK_INVALID_ID',
  BOOK_INVALID_ID: 'BOOK_INVALID_ID',
  UPDATE_RUNNING: 'UPDATE_RUNNING',
  UPDATE_BAD_ARCHIVE: 'UPDATE_BAD_ARCHIVE',
  CONVERTER_MISSING: 'CONVERTER_MISSING',
  SMTP_ERROR: 'SMTP_ERROR',
  SERVICE_NOT_READY: 'SERVICE_NOT_READY',
  UPDATE_LOG_READ_ERROR: 'UPDATE_LOG_READ_ERROR'
});

/** Ответ об ошибке с `ok: false`, машиночитаемым `code` и человекочитаемым `error`. */
export function apiFail(res, httpStatus, code, message, extra = {}) {
  res.status(httpStatus).json({ ok: false, code, error: message, ...extra });
}
